/*
 * dateproc.c   remote procedures; called by server stub
*/
#include <rpc/rpc.h> /* standard RPC include file */
#include "strs.h" /* this file is generated by rpcgen */


char ** upper_1_svc(input_data * data, struct svc_req *s)
{
    //printf("debug printf works!\n");
    static char * _stdout; /* must be static */
    char * one_string;
    size_t size;
    FILE * stream1, * stream2;
    char c;
    int i,j;
    char ** _argv;

    int num_strs = data->num_strs;

    _argv = (char **) malloc(num_strs*sizeof(char *));

    for (i = 0; i < num_strs; i++)
    {
      _argv[i] = (char *) malloc(16*sizeof(char));
      strcpy(_argv[i], data->argv[i]);
    }

    stream1 = open_memstream(&_stdout, &size);

    for (i = 0; i < num_strs; i++){
      printf("%s\n", _argv[i]);
      j = 0;
      stream2 = open_memstream(&one_string, &size);
      do
      {
        c = _argv[i][j];
        if (c >= 'a' && c <= 'z')
          c -= 0x20;
        printf("here: %c, %d\n", c, j);
        fprintf(stream2, "%c", c);
      } while(c != '\0' && j++ < 256);
      fflush(stream2);
      fclose(stream2);
      fprintf(stream1, "%s ", one_string);
      fflush(stream1);
      printf("%s\n", _stdout);
    }

    fclose(stream1);

    for (i = 0; i < num_strs; i++){
        free(_argv[i]);
    }
    free(_argv);

    return(&_stdout);
}
