/*
 * dateproc.c   remote procedures; called by server stub
*/
#include <rpc/rpc.h> /* standard RPC include file */
#include "strs.h" /* this file is generated by rpcgen */


char ** upper_1_svc(input_data * data, struct svc_req *s)
{
    //printf("debug printf works!\n");
    static char * _stdout; /* must be static */
    char * one_string;
    size_t size;
    FILE * stream;
    char c;
    int i;

    stream = open_memstream(&one_string, &size);

    int num_strs = data->num_strs;

    if (num_strs > 0)
      fprintf(stream, "%s ", data->argv0);
    if (num_strs > 1)
      fprintf(stream, "%s ", data->argv1);
    if (num_strs > 2)
      fprintf(stream, "%s ", data->argv2);
    if (num_strs > 3)
      fprintf(stream, "%s ", data->argv3);

    fflush(stream);
    fclose(stream);

    stream = open_memstream(&_stdout, &size);

    i = 0;
    do
    {
      c = one_string[i];
      if (c >= 'a' && c <= 'z')
        c -= 0x20;
      fprintf(stream, "%c", c);
    } while(c != '\0' && i++ < 256);

    fflush(stream);
    fclose(stream);

    return(&_stdout);
}
