/*
 * dateproc.c   remote procedures; called by server stub
*/
#include <rpc/rpc.h> /* standard RPC include file */
#include "strs.h" /* this file is generated by rpcgen */


char ** upper_1_svc(char ** str, struct svc_req *s)
{
    //printf("debug printf works!\n");
    static char * _stdout; /* must be static */
    size_t size;
    FILE * stream;
    char c;
    int i;

    stream = open_memstream(&_stdout, &size);

    i = 0;
    do
    {
      c = (*str)[i];
      if (c >= 'a' && c <= 'z')
        c -= 0x20;
      fprintf(stream, "%c", c);
    } while(c != '\0' && i++ < 256);

    fflush(stream);
    fclose(stream);

    return(&_stdout);
}
