/*
 * dateproc.c   remote procedures; called by server stub
*/
#include <unistd.h>
#include <time.h>
#include <rpc/rpc.h> /* standard RPC include file */
#include "date.h" /* this file is generated by rpcgen */

/*
 * Return the binary date and time
*/

long *bin_date_1_svc(void *arg, struct svc_req *s)
{
    static long timeval; /* must be static */
    timeval = time((long *) 0);
    return(&timeval);
}

/*
* Convert a binary time and return a human readable string
*/

char ** str_date_1_svc(long *bintime, struct svc_req *s)
{
    //printf("debug printf works!\n");
    static char * ptr; /* must be static */
    size_t size;
    FILE * stream;

    stream = open_memstream(&ptr, &size);

    fprintf(stream, "%s", ctime((const time_t *)bintime)); /* convert to local time */
    fprintf(stream, "%s", ctime((const time_t *)bintime)); /* convert to local time */
    fflush(stream);
    fclose(stream);

    return(&ptr);
}
